### ISSUE TITLE
Binding symbol arguments

### ISSUE THREAD

**Issue by CohenCyril** [LPCIC/coq-elpi#107]
Can we add parsing for arbitrary symbols so that
`Elpi foo x := a.`
has arguments `[str ":=", str "a"]` ?

**Comment by gares** [comment]
I've been thinking about it too.
But don't you want `Elpi foo Definition x : T := bo` as we do for records?

**Comment by gares** [comment]
(I mean, `: T` is optional... you may want binders after `x` ....)

**Comment by CohenCyril** [comment]
> I've been thinking about it too.
> But don't you want `Elpi foo Definition x : T := bo` as we do for records?

I think I want it too, especially to use a command as an attribute for definitions...
But I think I would like to be able to parse telescopes without the necessity to have := in the end... but maybe I am too greedy...
