### ISSUE TITLE
infixr leaks from databases

### ISSUE THREAD

**Issue by manmatteo** [LPCIC/coq-elpi#112]
An infixr declaration contained inside a Database seems to be applied to all subsequent Elpi tactics, regardless of whether that database was actually accumulated. This potentially makes typechecks successful even though the type was not correctly specified.

**Comment by gares** [comment]
I'm afraid this is a limitation of camlp5 :-/

I hope I will be able to replace camlp5 with menhir, be this will also force me do define once and forall a bunch on infix that will be always there (but possible have no associated clause/type).

**Comment by gares** [comment]
To be more precise:  Inf/Pre/Postfix declarations are global.

**Comment by Blaisorblade** [comment]
Done by https://github.com/LPCIC/coq-elpi/pull/350 ?
