### ISSUE TITLE
clarify nuparams in `Inductive` argument

### ISSUE THREAD

**Issue by gares** [LPCIC/coq-elpi#144]
In Coq there is no syntax to distinguish between Uniform and Non-Uniform parameters to Inductives. Coq infers it by their usage in the types of the constructor. This is not orthogonal to implicits, since an implicit status may make a parameter automatically inferred (as Uniform?).

This is too complex for Elpi's "inductive" argument, IMO, and also does not reflect how inductives are represented in Elpi: Uniform parameters *do not* occur as arguments to the inductivetype in the type of the constructors (they are fixed, why should you repeat them?), while Non-Uniform (and indexes) *must* appear (they vary, you must tell Elpi how). Coq-Elpi 1.3 only supports `Record` arguments, but I'd like to support also `Inductive` in 1.4 (to be released in few weeks).

I'm leaning toward imposing this very discipline for inductives used as arguments to Elpi commands.
Eg:
```coq
Elpi mycommand
  Inductive ty UP NuP : idx -> Type :=
  | K1 : ty (NuP * NuP) i -> ty NuP j
  | K2.
```
This also makes type checking of constructor with no given type for the conclusion (K2), it is
sufficient to unify they missing type with `ty NuP _` (in this case the index is not inferrable, while the exact argument NuP is exactly what makes NuP a parameter and not an index, but that is the idea, I hope it is understandable).

This is not ideal, since one cannot just prefix any Coq Inductive declaration with, say, `Elpi derive` since he may had implicits on, or use `@` and pass all arguments. But at the same time this design is very simple. The alternative is to have Elpi call the implicit argument machinery during the interning phase (note that Coq does intern + pretype inductive in a mixed way, so Elpi is already running its own code for inductives, since it has to stop after interning.. but so far this code is small, calling impargs does not not really thrill me).

Before committing to this design/compromise I'd love to hear from @maximedenes / @SkySkimmer  since IIRC they did clean up a little inductive + implicits recently.

**Comment by SkySkimmer** [comment]
>In Coq there is no syntax to distinguish between Uniform and Non-Uniform parameters to Inductives.

What about https://github.com/coq/coq/pull/11600 ?

**Comment by gares** [comment]
The new syntax is great!
Wasn't there something about implicits as well?

**Comment by SkySkimmer** [comment]
Not sure what you mean about implicits, maybe https://github.com/coq/coq/pull/11235 or https://github.com/coq/coq/pull/11579

**Comment by gares** [comment]
Definitely the second one. Unfortunately it does not document exactly how things are now. I'll look at the code.

**Comment by gares** [comment]
The conclusion is that non-uniform params will have to be declard by a |.
I'm also changing a lot the representation of an inductive declaration, so that implicit arguments manual settings are visible to elpi.
