### ISSUE TITLE
Data.Conversion.TypeErr when coq.typecheck is resumed on partial term

### ISSUE THREAD

**Issue by manmatteo** [LPCIC/coq-elpi#189]
While reconstructing a term, a constraint (declared by coq-elpi) gets resumed after I unify it with a partially instantiated term. However the constraint reactivation leads to a typecheck that has little information available and crashes with an uncaught exception.
It seems that the constraint was there since I had used `coq.term->string` on the variable. Indeed, removing that pretty printing gets around the issue.

Trace of the resume:
```
run 181 {{{  
	        
  rid:0 step:181 gid:210 user:curgoal = X58 = global (indc X72^2) 
	                                    
  rid:0 step:181 gid:210 user:rule = backchain 
	                                 
  rid:0 step:181 gid:210 user:candidates = File "elpi-builtin.elpi", line 17: 
	                                       
}}} ->  (0.000s)
select 112 {{{  
	           
  rid:0 step:181 gid:210 user:select = File "elpi-builtin.elpi", line 17: 
	                                   = A0 A0 :- . 
                                       
  rid:0 step:181 gid:0 user:assign = A0 := X58 
	                                 
  rid:0 step:181 gid:0 user:assign(expand) = X72^2 := X78 c0 c1 
	                                         
  rid:0 step:181 gid:0 user:assign(restrict) = 0 X78 c0 c1 := c0 \ c1 \ .X79 
                                               
  rid:0 step:181 gid:0 user:assign = X58 := global (indc X79) 
	                                 
  rid:0 step:181 gid:0 user:assign(resume) = 162 
	                                         
}}} ->  (0.000s)
run 182 {{{  
	        
  rid:0 step:182 gid:162 user:resume = evar (global (indc X79)) X60 (global (indc X79)) 
                                       
  rid:0 step:182 gid:211 user:rule = resume 
	                                 
}}} ->  (0.000s
```

Trace of the crash point:
```
run 187 {{{  
	        
  rid:0 step:187 gid:221 user:curgoal = coq.typecheck (global (indc X79)) X80^2 ok 
                                        
  rid:0 step:187 gid:221 user:rule = builtin 
	                                 
}}} error: Elpi__Data.Conversion.TypeErr(_, 0, _)  (0.000s)
The command has indeed failed with message:
Anomaly "Uncaught exception Elpi__Data.Conversion.TypeErr(_, 0, _)."
```

**Comment by gares** [comment]
Thanks for the report. One problem here is that the term you are passing to Coq cannot be represented in Coq. Coq terms can miss a sub-term, while here you lack an inductive type name. In other words a sub term of type `term` can be omitted, not a sub term of type `constructor`. In `(global (indc X79))` the variable `X79` is not of type `term`, but of type `constructor`.

I'll make the error message more clear, but I guess you also have a problem in your code, you should not be building `(global (indc X))` for an unassigned `X`. Does my explanation make sense?

**Comment by gares** [comment]
Said otherwise `(indc X)` is rarely built by hand, incrementally. It comes from `coq.locate` or similar which fills `X` in as well.

**Comment by manmatteo** [comment]
Yes, this perfectly makes sense, thanks! Indeed in the current situation the assignment `X58 = (global (indc X79))` seems silly; however it is there because (in logic programming style) I would like to reuse the same code for the case when `X58` is a real term and I want to extract the constructor before continuing.

In any case I am not attempting to print at this point: the typecheck is resumed only because I had printed `X58` at a previous point using `coq.term->string`. Is it necessary that `coq.term->string` places a constraint?

**Comment by gares** [comment]
I'd need to run your program to tell. If you give me instructions...

**Comment by manmatteo** [comment]
This is a minimal example where the issue happens:
```
Elpi Tactic test.
Elpi Accumulate lp:{{
solve _ _ _ :-
  coq.term->string X _,
  X = global (indc Y).
}}.

Goal True.
elpi test.
```
