### ISSUE TITLE
coq-elpi.dev does not build on `mathcomp-dev/coq-dev` image. 

### ISSUE THREAD

**Issue by chdoc** [LPCIC/coq-elpi#200]
I'm trying to set up CI using the `mathcomp/mathcomp-dev:coq-dev` docker image for a coq development using coq-elpi (hierarchy-builder), but I am getting build-failures when trying to use the aforementioned image. This is likely due to the pins in said image forcing opam into some strange solution that should not be supported, as I cannot reproduce the build failures locally or using the `coqorg/coq:dev` image. 

The Error:
```
File "src/coq_elpi_vernacular.mli", line 40, characters 9-29:
# Error: Unbound type constructor Constrexpr.sort_expr
# make[1]: *** [Makefile.coq:654: src/coq_elpi_vernacular.cmi] Error 2
# make: *** [Makefile:28: all] Error 2
```
The build with environment information: https://github.com/coq-community/graph-theory/pull/10/checks?check_run_id=1491723576

 CC: @gares

**Comment by gares** [comment]
The error seems due to the fact that your Coq is 8 days old, before this was merged https://github.com/coq/coq/pull/13415

**Comment by chdoc** [comment]
This isn't *my* Coq, locally everything works fine, it's the version of Coq in the `mathcomp/mathcomp-dev:coq-dev` docker image that seems to be stale indeed. So I suppose the conclusion is to not use these images for CI, although I now wonder what their purpose is then :man_shrugging: 

But thanks for documenting what the issue is/was.
