### ISSUE TITLE
Informational: coq-elpi.dev fails in Coq Platform master CI

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#203]
FYI: coq-elpi.dev fails to build in Coq Platform master CI since 2 days (it did work before).

See [GitHub CI Log](https://github.com/coq/platform/runs/1675213871?check_suite_focus=true#step:4:699)

See [Coq Platform tracker](https://github.com/coq/platform/issues/58)

**Comment by gares** [comment]
Fixed by the merge of #198
