### ISSUE TITLE
Coq Platform CI failure with coq-elpi master

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#208]
FYI: in the most recent nightly build of Coq platform master coq-elpi is failing on Ubuntu and MacOS - interestingly it still works on Windows 32 and 64.

Please see the CI transcripts here:

https://github.com/coq/platform/actions/runs/556372248

CI was running fine > 5 nightly builds before.

**Comment by gares** [comment]
Thanks for reporting, it looks like a race condition. I've released elpi 1.13 and coq-elpi 1.9 for Coq 8.13, and I'm updating the coq-master branch (the one used by the dev package) as part of https://github.com/coq/coq/pull/13847 (and its overlay)

**Comment by gares** [comment]
I don't know why, but I guess windows picked elpi 1.12 (elpi 1.13 was accepted in the opam repository yesterday)

**Comment by MSoegtropIMC** [comment]
It could have been a timing issue that the Windows test did run before the opam change was accepted. I will rerun the pipeline now and report the result.

**Comment by MSoegtropIMC** [comment]
Regarding Windows: since elpi is a main OCaml repo package, it will be delayed on Windows, since Windows uses a MinGW tailored copy of the main repo, which is usually a few days behind - sometimes more. To handle this I add patches to the Coq Platform local patch repo. Should I do this for elpi?

**Comment by gares** [comment]
Given the nature of the problem, I would not mind and wait the win repo to synchronize. But if you want a green light right away, I've nothing against.
