### ISSUE TITLE
More reduction machines

### ISSUE THREAD

**Issue by pi8027** [LPCIC/coq-elpi#228]
I wish to have an Elpi predicate for `native_compute`. I guess the situation is slightly different from others, since if `native_compute` is really available or not depends on the corresponding build option of Coq.

Also, can we have a reduction machine that behaves exactly the same as the `lazy` tactic? While `coq.reduction.lazy.whd_all` computes the weak-head normal form of a given term, the `lazy` tactic normalizes a given term by recursively applying the call-by-need strategy. I think it is "possible" to implement the same procedure in Coq-Elpi, but we have to embed and read back a subterm in each recursion step to do that, which can be really costly in some cases I guess.

(I really wish to have the former one. But, not to have the latter one is probably fine with me. So it is just a question for now.)

**Comment by gares** [comment]
Hum, ok, I can expose native and *.norm. If native is off, then it should default to vm automatically, maybe I'll expose a way to know if this is the case.

**Comment by gares** [comment]
Actually, I thought I had native already...
