### ISSUE TITLE
Document how to compile against a local Coq version

### ISSUE THREAD

**Issue by maximedenes** [LPCIC/coq-elpi#23]
Context: I want to prepare a patch for `coq-elpi` in view of a change on Coq's side.

I have a local Coq tree and I want to compile `coq-elpi` against it. The corresponding `coqc` is in the path, but when I run `make`, `coq-elpi` starts cloning Coq without asking me anything.

About installation, the `README` mentions only:

``
[blabla OPAM blabla]

You can also clone this repository and type `make` (in this case the plugin is compiled against the Coq version in the `coq/` submodule directory).
``

Could you document how to build `coq-elpi` against a local tree?  I had a brief look at the Makefile, but got lost in the hacks. It seems you rely on the location of the file produced by Coq's configure, for example. What is the point of all this? Superficially, it looks a bit like you are reimplementing some of the management of coq-elpi's dependencies in the `Makefile`...

**Comment by gares** [comment]
done
