### ISSUE TITLE
[derive] derive.param1 doesn't accept `let` in function definitions

### ISSUE THREAD

**Issue by Columbus240** [LPCIC/coq-elpi#262]
If `let` appears in a function definition, `derive.param1` doesn't work. After performing the substitution, the function is accepted.
```coq
From elpi.apps Require Import derive.

derive unit.

Definition foo (a : unit) : unit :=
  let b := a in
  a.

Definition bar (a : unit) : unit :=
  a.

Fail Elpi derive.param1 foo.
Elpi derive.param1 bar.
```

Coq v8.13.2, coq-elpi v1.11.0

**Comment by gares** [comment]
Thanks for reporting, this is clearly a bug, it should be easy to fix.
