### ISSUE TITLE
[derive] Coq stdlib

### ISSUE THREAD

**Issue by gares** [LPCIC/coq-elpi#263]
have a file such that `From elpi.apps Require Import derive.stdlib` is enough to use derive on new types that mentions Coq's stdlib ones (eg list, prod...)

**Comment by Columbus240** [comment]
Regarding #265: I think it’d be best, if this `derive.stdlib` wouldn't add a new `option_map` but would use the definition of the stdlib. This way the user doesn't have to deal with two different functions with identical definitions & behaviour.
