### ISSUE TITLE
Please create a tag for the upcoming release of Coq 8.14

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#291]
The Coq team released Coq 8.14+rc1 on September 17, 2021
and plans to release Coq 8.14.0 before October 31, 2021.
A corresponding Coq Platform releases should be released before November 30, 2021.
It can be dealyed in case of difficulties until January 31, 2022, but this should be an exception.

Coq CI is currently testing commit 60db122c8009b04f1bc44c2466a737e55ebe4b6a
on branch https://github.com/LPCIC/coq-elpi/tree/coq-master
but we would like to ship a released version instead (a tag in git's slang).

Coq Platform is currently *not testing* this package!

Could you please create a tag, or communicate us any existing tag that works with
Coq branch v8.14, preferably 15 days before November 30, 2021
or earlier? In case we might have to delay the Coq Platform release cause of issues with
your project, we would prefer to be informed about the situation as early as possible.

Thanks!

P.S.: this issue has been creates semi-automatically.

CC: https://github.com/coq/platform/issues/139

**Comment by gares** [comment]
`v1.11.2` works with Coq `8.14+rc1`

**Comment by MSoegtropIMC** [comment]
Thanks!

So for 2021.09~8.13 I use 1.11.1 and for 2021.09~8.14 I use 1.11.2?

**Comment by gares** [comment]
yes
