### ISSUE TITLE
Weird interaction between Coq-Elpi's tactic arguments and Ltac's Tactic Notation features

### ISSUE THREAD

**Issue by cloudyhug** [LPCIC/coq-elpi#292]
Consider a `t` elpi tactic doing nothing and 2 notations so that the first argument is recognised as a term and not a string / name / whatever.
```coq
Elpi Tactic t.
Elpi Accumulate lp:{{
  solve _ _.
}}.
Elpi Typecheck.

Tactic Notation "t1" constr(h) := idtac h.
Tactic Notation "t2" constr(h) := elpi t (h).
```
When I use this tactic with a local variable such as a hypothesis, I get a weird behaviour.
```coq
Section Test.
  Hypothesis H : True.
  Lemma foo : True.
  Proof.
    t1 H. (* first tactic, works *)
    elpi t (H). (* expected equivalent of t2, works *)
    t2 (H = H). (* t2 called with a term containing H, works *)
    t2 H. (* called just with H, fails *)
```
```
Free Coq variable H in context
```
Do you know whether this comes from Ltac, Coq-Elpi, or both? Is there a specific behaviour in Ltac's parser for single variables, that remains enabled even when redefining a tactic notation, and gives an output that Coq-Elpi cannot understand?

Thanks!

**Comment by gares** [comment]
looks like a bug in elpi, thanks for reporting.

**Comment by gares** [comment]
I did update the doc
  https://github.com/LPCIC/coq-elpi/commit/79dbdb1bb1841e456c10d4bb5ff4d19f3895dce2
maybe I could make both work, but the interaction with Ltac is so tricky that I prefer to document how things are.
