### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#306]
There are typos here and there in the sources, which lintian pointed out and I'm preparing a patch.

**Comment by SnarkBoojum** [comment]
[fix_typos.txt](https://github.com/LPCIC/coq-elpi/files/7522499/fix_typos.txt) is supposed to fix all typos, but lintian still finds a ouput vs output somewhere

**Comment by gares** [comment]
Thanks.
The ones in elpi-builtin are to be fixed in elpi, not coq-elpi. I think I fixed them already, but did not release.

The others should be fixed in src/coq_elpi_builtins.ml, since the .elpi file is generated.

**Comment by gares** [comment]
I want them to be there for documentation purposes. Typing make regenerates them if needed (they are generated from .ml files, so it is very hard to get the out of sync, since you need to compile the .ml files if you edit them).

**Comment by SnarkBoojum** [comment]
My patch is still relevant with 1.12.1.
