### ISSUE TITLE
Make install doesn't seem to respect DESTDIR everywhere

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#307]
Trying to package coq-elpi for Debian, I have issues with the Makefile install targets: I get quite a few failures because it tries to install things directly on the filesystem, with paths not getting prepended with $(DESTDIR) correctly.

Here is a log of a build:
[coq-elpi.log](https://github.com/LPCIC/coq-elpi/files/7558015/coq-elpi.log)

**Comment by gares** [comment]
thanks I'll look into this asap

**Comment by gares** [comment]
the bug is here https://github.com/LPCIC/coq-elpi/blob/7e626bc4b9b0734286d763fa5fdf5791bde6d33d/Makefile.coq.local#L21 but I cant fix it right now
