### ISSUE TITLE
src/coq_elpi_builtins_HOAD.ml says it's autogenerated... how?

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#308]
The first line says: "Automatically generated from elpi/coq-HOAS.elpi, don't edit".

It should document how it is generated -- and if it's built, it probably shouldn't be shipped.

**Comment by gares** [comment]
Right, this file should not be there.

It is generated by this rule:
https://github.com/LPCIC/coq-elpi/blob/7e626bc4b9b0734286d763fa5fdf5791bde6d33d/Makefile.coq.local#L4
