### ISSUE TITLE
Missing META file

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#312]
I thought META files were needed to make things ocamlfind-able, and the Debian Ocaml Policy says I should write one when there is none ; should I do so or do I miss something?

**Comment by gares** [comment]
coq-elpi is today not loaded using findlib, since Coq does not use it yet (see https://github.com/coq/coq/pull/15220).
In the future it will, and I'll add a META myself.

**Comment by Blaisorblade** [comment]
This is probably fixed? Either now or starting with Coq 8.16?

**Comment by gares** [comment]
In 8.16 it will be ok

**Comment by gares** [comment]
Fixed in 1.15.x
