### ISSUE TITLE
Enrich `Elpi Accumulate File` to search `From` some logical Coq path

### ISSUE THREAD

**Issue by jhaag** [LPCIC/coq-elpi#336]
Currently coq-elpi uses the [following function](https://github.com/LPCIC/coq-elpi/blob/master/src/coq_elpi_vernacular.ml#L180) in order to generate the valid paths with which to search when invoking `Elpi Accumulate File`. In short, this function results in the following list of search paths: `[./., ./.., ......lib/elpi, ......user-contrib/elpi]`; of note is the fact that `./.` and `./..` are interpreted **relative to the directory in which the coqc process was invoked**.

Not only does this behavior break Emacs Proof General clients who wish to step over such commands - since Proof General (seemingly) starts the coqc process from the directory containing the file being stepped through - but it also breaks CI setups in which the build occurs in a location that differs from that which developers use locally. At least the latter of these issues is a major blocker for use of `Elpi Accumulate File` within my team (and I am personally affected by the former, although many on my team would be unaffected). 

[This Zulip thread](https://coq.zulipchat.com/#narrow/stream/253928-Elpi-users.20.26.20devs/topic/.60Elpi.20Accumulate.20File.60.20and.20Coq's.20.60LoadPath.60/near/270211136) contains the initial question which prompted the creation of this issue; [a subsequent comment](https://coq.zulipchat.com/#narrow/stream/253928-Elpi-users.20.26.20devs/topic/.60Elpi.20Accumulate.20File.60.20and.20Coq's.20.60LoadPath.60/near/270237017) that I made outlined a plausible solution which @gares plans to investigate. The proposed solution involves a new piece of Elpi Vernacular of the form `Elpi Accumulate File FILE From LOGICAL_PATH` and would have the semantics "Accumulate the `.elpi` file `FILE` relative to the physical path referenced by the Coq logical path `LOGICAL_PATH`".

**Comment by gares** [comment]
I did have it in a branch, but there is a caveat. Some, if not all, logical paths are mapped multiple times.
For example `elpi.apps.derive` is mapped to `./apps/derive/theories/derive` but also to `/home/gares/.opam/.../coq/user-contribs/elpi/apps/derive`.

It seems Coq respects the order, so the local one comes first, but I need to think a bit more about this...

**Comment by jhaag** [comment]
Could we just add all potential matches to the list that we try to search in? This semantics is certainly strange, but it might still be more practically useful than what is implemented at the moment.

**Comment by gares** [comment]
I think I'll look for the file in every path. If more than one exist, I'll error (you don't install .elpi files, since they are embedded in the .vo).

I want to avoid ambiguity. Would that work in uour setup?

**Comment by jhaag** [comment]
Yes, that should work for us. At the moment all of our internal logical paths map to a single physical path, and I anticipate that this will remain the status quo. If/when we package and distribute more of our proofs/infrastructure, the `.elpi` files would not be installed in multiple places, as you point out.

Just to be clear, the physical paths that you search be restricted to those in the preimage of the logical path, right? I'd hate to conflict with files distributed via coq-elpi itself :~)

**Comment by gares** [comment]
If you use the new From clause, then yes. Anyway Ill open a PR an get feedback there

**Comment by gares** [comment]
The PR is open, even if it is "multipurpose" #339
