### ISSUE TITLE
Build system inconsistency

### ISSUE THREAD

**Issue by jwintz** [LPCIC/coq-elpi#371]
Trying to update the master branch, I can't get the branch to build.

https://github.com/LPCIC/coq-elpi/blob/89c534330cfd225f695ad7e0731abf1477b973bd/Makefile#L114

Looks like `Makefile.coq.conf` is missing.

**Comment by gares** [comment]
Hum, that is weird since coq_makefile should have generated both Makefile.coq and Makefile.coq.conf.
Can you start from a fresh checkout?

**Comment by gares** [comment]
https://github.com/LPCIC/coq-elpi/blob/89c534330cfd225f695ad7e0731abf1477b973bd/Makefile#L93

**Comment by gares** [comment]
we changed the build system
