### ISSUE TITLE
`coq.say` should honour `Set Printing Width`

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#397]
It would be nice if `coq.say` would honour `Set Printing Width` or alternatively if there would be another way to set the printing width. I frequently print terms where the default width results in vertically serialised symbols because the indent exceeds the printing width.

**Comment by gares** [comment]
Not using `Set Printing Width` as the default is an oversight on my side, I'll push a fix to the #395 branch later.

In any case you have all the API you need to print terms using Coq's box model, look for `coq.pp`and `coq.pp->string` in the coq-builtin.elpi file. Note that `term->string` already accepts a printing width, just load the context with `@ppwidth!` before calling it.
Eg
```elpi
@ppwidth! 160 => coq.say {coq.term->string T}.
```

**Comment by gares** [comment]
I think this is fixed in the 1.16 release
