### ISSUE TITLE
Get arguments for tactic of form `simple_intropattern_list(x)`

### ISSUE THREAD

**Issue by lukovdm** [LPCIC/coq-elpi#505]
I need to write an Intro tactic that also allows for receiving normal intro patterns and also my own intro patterns. To be able to properly accept an intro pattern, I need to have a notation in the form of:
```coq
Tactic Notation "eiIntros" "(" simple_intropattern_list(x) ")" :=
  elpi eiIntros x.
```
amongst other notations.
It would thus be nice to be able to read in an intro pattern list, be able to manipulate it when necessary and pass it on to the intro tactic.

**Comment by gares** [comment]
Sorry, the implicit question is: would the first approach suffice for your use case?

**Comment by lukovdm** [comment]
Yes, I think this would work. I only need to call intros on an intro pattern that I have been given by the user on the tactic for now.
Thus my notation would become:
```coq
Tactic Notation "eiIntros" "(" simple_intropattern_list(x) ")" :=
  let coqintro := intros x in
  elpi eiIntros coqintro "".
```

**Comment by lukovdm** [comment]
After having a talk with my supervisor, I'm sorry to say, it turns out we actually do need to have full access to the intro pattern data type. We have to pull it apart and apply our own steps in between applications of parts of the intro pattern. Also we would need to create new ones from scratch. Would this be possible?
