### ISSUE TITLE
coq.gref.set: a filter function and a function for creating from list might be useful

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#549]
I frequently need a filter function for `coq.gref.set` and a function to create from a list a `coq.gref.set`.

One can of course write these in Elpi, but I am unsure what the efficiency would be compared to a native implementation. Especially for filter I have to convert the set to a list, filter the list and then reconstruct the set element by element.

In case you expect that the performance difference is less than say 2 or 3, it is fine for me.

**Comment by gares** [comment]
I coded the scaffolding in Elpi, the difference in perf is about 3x for set filtering for example.

Having the possibility to define HO external predicates is nice anyway, so I'll merge it even if for sets and maps the perf gain is not very important.
