### ISSUE TITLE
Failing test from elpi 1.18.1 to coq-elpi 1.19.3

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#559]
While checking if the newer elpi worked with the next Debian packages (transition to coq 8.18 and MC 2 is still stuck with mathcomp-abel and mathcomp-analysis), I got the following error on coq-elpi:
```
test link order
--- tests/test_link_order_import3.ref   2023-10-12 14:06:10.000000000 +0000
+++ tests/test_link_order_import3.txt   2023-12-06 10:41:04.054791445 +0000
@@ -116,6 +116,8 @@
 std.split-at _ _ _ _ :- std.fatal-error split-at run out of list items.
 std.fold [] A0 _ A0.
 std.fold [A0 | A1] A2 A3 A4 :- A3 A0 A2 A5 , std.fold A1 A5 A3 A4.
+std.fold-right [] A0 _ A0.
+std.fold-right [A0 | A1] A2 A3 A4 :- std.fold-right A1 A2 A3 A5 , A3 A0 A5 A4.
 std.fold2 [] [_ | _] _ _ _ :-
  std.fatal-error fold2 on lists of different length.
 std.fold2 [_ | _] [] _ _ _ :-
```

**Comment by gares** [comment]
That is fine, the list of builtins also come from elpi.
I guess you have a more recent elpi than what is currently required. Maybe you are on elpi 8.18? I plan to make it the requirement for coq-elpi 2.0, to be released soon.
