### ISSUE TITLE
Port param to the new API for databases

### ISSUE THREAD

**Issue by gares** [LPCIC/coq-elpi#6]
It is not possible to ask elpi to accumulate a clause to a database
  https://github.com/LPCIC/coq-elpi/blob/eb9302da09e04d0c55cf3e0dacaa846152755113/coq-api.elpi#L437
and have a program automatically load a database
  https://github.com/LPCIC/coq-elpi/blob/eb9302da09e04d0c55cf3e0dacaa846152755113/theories/tests/test_API.v#L346

I think the code of param1 and param2 should be ported to that API

**Comment by CohenCyril** [comment]
"It is not possible" -> "It is **now** possible"?

**Comment by gares** [comment]
eh eh, yes, with elpi everything is possible ;-)

**Comment by gares** [comment]
After a short discussion, it seems the database is also needed in Coq, for TC resolution, so paramX shall stay like that.
