### ISSUE TITLE
Declaring TC instance in section can throw anomaly on closing

### ISSUE THREAD

**Issue by trilis** [LPCIC/coq-elpi#618]
Here is the minimal example:
```
From elpi Require Import elpi.
Require Import String.

Class Show (A : Type) :=
  { show : A -> string }.
Definition String_Show : Show string := {|
    show := id
|}.

Elpi Command ElpiStart.
#[synterp] Elpi Accumulate lp:{{
    main _ :-
        coq.env.begin-section "A".
}}.
Elpi Accumulate lp:{{
    main _ :-
        coq.env.begin-section "A".
}}.
Elpi Typecheck.
Elpi Export ElpiStart.

Elpi Command ElpiTCEnd.
#[synterp] Elpi Accumulate lp:{{
    main _ :-
        coq.env.end-section.
}}.
Elpi Accumulate lp:{{
    main _ :-
        coq.locate "String_Show" I,
        @global! => coq.TC.declare-instance I 0,
        coq.env.end-section.
}}.
Elpi Typecheck.
Elpi Export ElpiTCEnd.

ElpiStart.

ElpiTCEnd.
```

On the ending of the section, I get this anomaly:
```
Error: Anomaly
"File "tactics/hints.ml", line 1301, characters 6-12: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```
It seems like some hints are replayed when they shouldn't.
Note that everything works fine when we do `declare-instance` and `end-section` in separate commands, or when we do everything (`begin-section`, `declare-instance` and `end-section`) in one command, or when we remove `@global!`.
Coq 8.19.1, coq-elpi 2.1.0. We definitely didn't have this issue before synterp introduction.

**Comment by gares** [comment]
It seems the bug is in Coq, file `classes.ml`, and that is was introduced by the parsing/execution phase split.
The code below should use `Global.sections_are_opened ()` instead of `Lib.sections_are_open ()`:
```ocaml
let add_instance_base inst =
  let locality = match inst.locality with
  | Local -> Local
  | SuperGlobal ->
    (* i.e. in a section, declare the hint as local since discharge is managed
       by rebuild_instance which calls again add_instance_hint; don't ask hints
       to take discharge into account itself *)
    if Lib.sections_are_opened () then Local
    else SuperGlobal
  | Export ->
    (* Same as above for export *)
    if Lib.sections_are_opened () then Local
    else Export
  in
  add_instance_hint inst.instance ~locality
    inst.info
```
CC @janno @rlepigre that may be impacted too.
Note that the erroneous code path is only taken if one passes `@globa!` (that corresponds to SuperGlobal).

I did not test a fix, so I'm only speculating, but it seems plausible.

Thanks for reposting.

**Comment by trilis** [comment]
Sure, I'll try to patch. Thanks to pointing out to the relevant code.

**Comment by trilis** [comment]
I can confirm that the anomaly in the minimized example is gone with the proposed fix. However, when trying to apply this fix to our real code, I found another anomaly:
```
From elpi Require Import elpi.
Require Import String.

Class Show (A : Type) :=
  { show : A -> string }.

Elpi Command ElpiTest.
#[synterp] Elpi Accumulate lp:{{
    main _ :-
        coq.env.end-module _.
}}.
Elpi Accumulate lp:{{
    main _ :-
        coq.env.add-const "x"
            {{ Build_Show string (@id string) }} 
            {{ Show string }} @transparent! _,
        coq.locate "x" G,
        coq.TC.declare-instance G 0,
        coq.env.end-module _.
}}.
Elpi Typecheck.
Elpi Export ElpiTest.

Module A. 
ElpiTest.
```

We get 
```
Error: Anomaly "Constant Test.x does not appear in the environment."
Raised at Exninfo.iraise in file "clib/exninfo.ml", line 79, characters 4-11
Called from Environ.lookup_constant in file "kernel/environ.ml" (inlined), line 217, characters 6-34
Called from Typeops.type_of_global_in_context in file "kernel/typeops.ml", line 598, characters 13-42
Called from Classes.existing_instance in file "vernac/classes.ml", line 300, characters 20-59
...
```
So it looks like the anomaly is thrown when declaring instance. Maybe there is some case of FQN confusion? Because it probably shouldn't be `Test.x`, it should be `Test.A.x` (`Test` is the name of my file). But changing locate string to "A.x" results in locate failure. Note that synterp code closing the module is essential to reproduce this — can it be that closing module in synterp somehow messes with interp code?

(Of course, one can easily circumvent this issue by using output of add-const instead of locating, but I think it's an interesting finding nevertheless)

**Comment by gares** [comment]
Could you please open another bugreport, this is about locate and not TC. The bug could be as well in Coq.
It would also be nice if you could provide your TC patch, or directly submit it to Coq.

**Comment by trilis** [comment]
Sure, I created separate bugreport and submitted PR to coq repo
