### ISSUE TITLE
Release version compatible with Coq 8.20

### ISSUE THREAD

**Issue by SnarkBoojum** [LPCIC/coq-elpi#686]
(I'm trying to update the Coq ecosystem in Debian, so I'm looking for a set of coherent official releases)

**Comment by gares** [comment]
The last release works with 8.20

**Comment by SnarkBoojum** [comment]
Hmmm... I have packaged Coq 8.20.0, elpi 1.19.6 and trying to compile coq-elpi 2.2.3, compilation fails:
```
CAMLC -c src/coq_elpi_utils.mli
File "src/coq_elpi_utils.mli", line 24, characters 15-98:
24 |   EConstr.t -> (EConstr.t,EConstr.types,EConstr.ESorts.t, EConstr.EInstance.t) Constr.kind_of_term * EConstr.t array
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: The type constructor "Constr.kind_of_term" expects 5 argument(s),
       but is here applied to 4 argument(s)
```
but indeed, line 24 shouldn't apply because there's a [%%if coq = "8.19"] to guard it... so somehow the version detection must be off... I'll need to search why.

**Comment by SnarkBoojum** [comment]
Ah, no, my mistake, that was coq-elpi 2.1.0, I used what is currently in Debian and not the future 2.2.3 package - let me retry with the correct sources...

**Comment by SnarkBoojum** [comment]
Sigh... now it just works, sorry for the noise...
