### ISSUE TITLE
Broken in Coq CI

### ISSUE THREAD

**Issue by SkySkimmer** [LPCIC/coq-elpi#695]
eg https://gitlab.inria.fr/coq/coq/-/jobs/4772378
AFAICT it's since the merge of https://github.com/LPCIC/coq-elpi/pull/684

**Comment by rlepigre** [comment]
Seems like the removal of the `dune-workspace` file is responsible, but we don't want that file in `coq-elpi` itself. I could make `make ci-elpi` go through locally after doing `touch _build_ci/elpi/dune-workspace`, so I would advise you to do this from the Coq side.

**Comment by gares** [comment]
Thanks @rlepigre to suggest a quick fix on the coq side.
My understanding is that passing --root would also work, but I also recall that was implemented on the Coq side, so I'm a bit puzzled.

I will be travelling tomorrow, so don't expect any action on my side before Monday. @SkySkimmer @proux01 please try the workaround above, sorry for the disruption.
