### ISSUE TITLE
Broken in 4.06.0 [-safe-string]

### ISSUE THREAD

**Issue by ejgallego** [LPCIC/coq-elpi#7]
coq-elpi fails in newer OCaml version with 

```
OCAMLOPT elpi_custom.cmx            -c
File "elpi_custom.ml", line 187, characters 32-33:
Error: This expression has type string but an expression was expected of type
         bytes
```

**Comment by gares** [comment]
It is probably the String.length at https://github.com/LPCIC/elpi/blob/6e25725c02dc0b49145afe8b45916e7b02804095/src/elpi_custom.ml#L185
since the code calling this function seems to use Bytes... I'll give it a try tomorrow.

**Comment by ejgallego** [comment]
Grazie!
