### ISSUE TITLE
coq-elpi.dev doesn't compile 

### ISSUE THREAD

**Issue by aleksnanevski** [LPCIC/coq-elpi#722]
Hi. I was trying to upgrade my coqdev opam switch today, and ran into a problem that coq-elpi.dev stopped compiling. The error message is below. Not sure if I'm doing something wrong, so I would appreciate any advice on how to proceed. 

-----------------

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved elpi.1.19.6  (cached)
⬇ retrieved coq-elpi.dev  (no changes)
⊘ removed   elpi.2.0.4
∗ installed elpi.1.19.6
[ERROR] The compilation of coq-elpi.dev failed at "dune build -p coq-elpi -j 23 @install".

\#=== ERROR while compiling coq-elpi.dev =======================================#
\# context     2.2.1 | linux/x86_64 | ocaml-option-flambda.1 ocaml-option-fp.1 ocaml-variants.5.2.1+options | https://coq.inria.fr/opam/extra-dev#2024-11-29 14:29
\# path        ~/.opam/coqdev/.opam-switch/build/coq-elpi.dev
\# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p coq-elpi -j 23 @install
\# exit-code   1
\# env-file    ~/.opam/log/coq-elpi-746167-f72773.env
\# output-file ~/.opam/log/coq-elpi-746167-f72773.out
\### output ###
\# 8 | type cunit = Full of  Names.KerName.t * Compile.compilation_unit | Signature of Compile.compilation_unit_signature
\# [...]
\# Error: Unbound type constructor "Compile.compilation_unit_signature"
\# (cd _build/default && /home/aleks2/.opam/coqdev/bin/ocamlopt.opt -w -40 -w -27 -g -I src/.elpi_plugin.objs/byte -I src/.elpi_plugin.objs/native -I /home/aleks2/.opam/coqdev/lib/coq-core/boot -I /home/aleks2/.opam/coqdev/lib/coq-core/clib -I /home/aleks2/.opam/coqdev/lib/coq-core/config -I /home/aleks2/.opam/coqdev/lib/coq-core/engine -I /home/aleks2/.opam/coqdev/lib/coq-core/gramlib -I /home/[...]
\# File "src/coq_elpi_utils.ml", line 28, characters 4-30:
\# 28 |     API.Ast.Loc.client_payload;
\#          ^^^^^^^^^^^^^^^^^^^^^^^^^^
\# Error: Unbound record field "API.Ast.Loc.client_payload"
\# (cd _build/default && /home/aleks2/.opam/coqdev/bin/ocamlc.opt -w -40 -w -27 -g -bin-annot -I src/.elpi_plugin.objs/byte -I /home/aleks2/.opam/coqdev/lib/coq-core/boot -I /home/aleks2/.opam/coqdev/lib/coq-core/clib -I /home/aleks2/.opam/coqdev/lib/coq-core/config -I /home/aleks2/.opam/coqdev/lib/coq-core/engine -I /home/aleks2/.opam/coqdev/lib/coq-core/gramlib -I /home/aleks2/.opam/coqdev/lib[...]
\# File "src/coq_elpi_utils.ml", line 28, characters 4-30:
\# 28 |     API.Ast.Loc.client_payload;
\#          ^^^^^^^^^^^^^^^^^^^^^^^^^^
\# Error: Unbound record field "API.Ast.Loc.client_payload"

**Comment by gares** [comment]
I need to update the dependency on elpi >= 2.0.3 in the .dev package

**Comment by gares** [comment]
https://github.com/coq/opam/pull/3220
