### ISSUE TITLE
Local windows builds fail with coq-elpi.2.2.3 (coq-elpi.2.1.0 was fine)

### ISSUE THREAD

**Issue by MSoegtropIMC** [LPCIC/coq-elpi#729]
I have issues building coq-elpi.2.3.3 locally on Windows. It does work on github servers (which use different paths) so this is likely a path normalization issue.

The error (a bit line breaked)  is:
```
Error:
Anomaly
"Uncaught exception Failure("File elpi2html.elpi not found in:
E:\\bin\\coq-platform_2025.01\\opam\\CP.2024.10.1~8.20~2025.01\\.opam-switch\\build\\coq-elpi.2.2.3\\_build\\default\\.,
E:\bin\\coq-platform_2025.01\\opam\\CP.2024.10.1~8.20~2025.01\\lib\\elpi,
E:\\bin\\coq-platform_2025.01\\opam\\CP.2024.10.1~8.20~2025.01\\.opam-switch\\build\\coq-elpi.2.2.3\\_build\\default\\.,
E:\\bin\\coq-platform_2025.01\\opam\\CP.2024.10.1~8.20~2025.01\\.opam-switch\\build\\coq-elpi.2.2.3\\_build\\default\\..
")."
Please report at http://coq.inria.fr/bugs/.
```
The actual path where elpi2html.elpi can be found is:
```
E:\bin\coq-platform_2025.01\opam\CP.2024.10.1~8.20~2025.01\lib\elpi\elpi2html.elpi
```
An important point is that in the paths above back slashes are escaped except for the first backslash in the correct path:
```
E:\bin\\coq-platform_2025.01\\opam\\CP.2024.10.1~8.20~2025.01\\lib\\elpi,
  ^ this is likely the culprit
```
Depending on how you use these paths, backslashes must be escaped. For this reason I prefer forward slashes which are natively supported by the Windows core APIs - just CMD does not support this.

Can you explain, how the second path in the above list is created and why the first backslash is not escaped, while all others are?

**Comment by gares** [comment]
Here:
https://github.com/LPCIC/coq-elpi/blob/e9ea40722f205c1c459b80bf2584355d8b3f91d4/src/dune#L33

I think it is not under my control. You can hack the string, after all it is an ocaml program.
*But* I'm about to release a new version that does not even use/need that file. So maybe it is not the best use of your time.

**Comment by gares** [comment]
released 2.3.0

**Comment by MSoegtropIMC** [comment]
I think we should anyway research what the issue in dune is - it will for sure come back to use some day. I will report this as issue in dune. But it will of course help that it need not be fixed before the Coq Platform release :-)

**Comment by MSoegtropIMC** [comment]
I had a look at the generated file and it is:
```
$ cat ./_build/default/src/coq_elpi_config.ml
let elpi2html = "E:\bin\coq-platform_2025.01\opam\CP.2024.10.1~8.20~2025.01\lib\elpi\elpi2html.elpi";;
$ ls -l 'E:\bin\coq-platform_2025.01\opam\CP.2024.10.1~8.20~2025.01\lib\elpi\elpi2html.elpi'
-rw-r--r-- 1 Michael None 11992 Dec  5 19:12 'E:\bin\coq-platform_2025.01\opam\CP.2024.10.1~8.20~2025.01\lib\elpi\elpi2html.elpi'
```
So nothing is escaped and the path as written to `coq_elpi_config.ml` exists. It appears to be an issue in elpi / coq-elpi that in cannot handle the path given in `coq_elpi_config.ml`. As a consequence I won't report in dune (for now).

**Comment by MSoegtropIMC** [comment]
A note: if you use the path in a call like `system` which does some sort of command line parsing, the backslashes must be escaped. In case it is used with spawn like functions which take the process name as string as is, it need to be escaped. As I said pretty much everything in Windows except the Windows command interpreter (CMD) can handle forward slashes and mixed forward / backward paths. This is in the core of Windows since ever (despite some folklore saying otherwise). So just using forward slashes is an option unless it ends up in `CMD`.

**Comment by MSoegtropIMC** [comment]
Sorry, please ignore my post with the dump of `coq_elpi_config.ml` - of course the path needs to be escaped if it goes into OCaml. I guess the problem is that OCaml implicitly escapes the \ in case the escape sequence is invalid. `\b` is likely a valid escape sequence (bell), the other characters following a \ probably not.

**Comment by MSoegtropIMC** [comment]
Isn't there a raw string syntax in OCaml? I can't find references to this right now but I think I have seen this. So one solution would be to use raw string quotes when you write the OCaml file in dune - assuming this really exists and I don't mix up languages.

**Comment by gares** [comment]
I guess `{| .... |}` should work

**Comment by MSoegtropIMC** [comment]
Ah - at the end of section `https://ocaml.org/manual/5.2/lex.html#sss:stringliterals`. So a fix would likely be to write in dune:
```
(echo "let elpi2html = {|%{lib:elpi:elpi2html.elpi}|};;")))))
```

**Comment by gares** [comment]
nice, so it you have to make a release with 2.2.3 you have a fix, but in 2.3.0 that line is gone

**Comment by MSoegtropIMC** [comment]
The version to pick is (mostly) the decision of the package maintainer. So if you say 2.3.0 is the best choice, I will pick it.

But it is anyway good to know what is going on and collect good practices (and refreshing that in OCaml "raw strings" are called "quoted strings").

**Comment by MSoegtropIMC** [comment]
Since this is fixed in the latest version, I will close this issue.

**Comment by gares** [comment]
> I guess the problem is that OCaml implicitly escapes the \ in case the escape sequence is invalid.

I'll save this one into my bad_ideas.txt file ;-)

**Comment by rlepigre** [comment]
Note that technically, you could probably decompose your rule into:
- a rule that produces an intermediate file `path.txt`, using just `(echo "%{lib:elpi:elpi2html.elpi})`,
- a rule generating the OCaml file using `(echo "let elpi2html = %{read-string:path.txt}")`.

The `%{read-string:...}` "variable" takes care of the escaping (see https://dune.readthedocs.io/en/latest/concepts/variables.html).
