### ISSUE TITLE
wish: syntax

### ISSUE THREAD

**Issue by gares** [LPCIC/coq-elpi#98]
`Elpi foobar [ 33 | "ident" | ident | (term) | Record <record-syntax> ] .`

**Comment by gares** [comment]
When real user extensible attributes will be there:
```
#[elpi(mixin)] Record ....
```

**Comment by gares** [comment]
It seems Cyril found a simpler way

**Comment by CohenCyril** [comment]
Nop, my solution only works because we do not have parameters yet!

**Comment by gares** [comment]
I checked the code and while parsing things is doable the whole "globalization" is a mess, hard to reuse.
In particular the two phases (intern and interp) are mixed. If we really need this feature, quite some work on the Coq side is needed as well.

**Comment by CohenCyril** [comment]
maybe I could write it as a (fun ... => ...), if only I could omit the `fun` keyword, `=>` symbol and parenthesis :laughing: ... well I would like to parse a telescope...
